import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Scanner;
 

 
class hash {
    public static byte[] getSHA(String input) throws NoSuchAlgorithmException
    {
       
        MessageDigest md = MessageDigest.getInstance("SHA-256");
 
        
        return md.digest(input.getBytes(StandardCharsets.UTF_8));
    }
     
    public static String toHexString(byte[] hash)
    {
        
        BigInteger number = new BigInteger(1, hash);
 
        
        StringBuilder hexString = new StringBuilder(number.toString(16));
 
        
        while (hexString.length() < 64)
        {
            hexString.insert(0, '0');
        }
 
        return hexString.toString();
    }
 
    public static void main(String args[])
    {
        try
        {
            System.out.println("HashCode Generated by SHA-256 for:");
            Scanner myObj = new Scanner(System.in); 
    		System.out.println("Enter text");

    		String text = myObj.nextLine();  
    		System.out.println("Hash: " + toHexString(getSHA(text))); 

 
        }
        // For specifying wrong message digest algorithms
        catch (NoSuchAlgorithmException e) {
            System.out.println("Exception thrown for incorrect algorithm: " + e);
        }
    }
}